<resources>
<string name="app_name">SUNMI Assistant</string>
<string name="str_login">Log in</string>
<string name="str_register">Register</string>
<string name="hint_input_user_name">Mobile or E-mail.</string>
<string name="tip_forget_psd">Forgot password</string>
<string name="str_sms_login">Use SMS to login</string>
<string name="textView_tip_psd">Please enter a password containing a mix of letters and numbers with length between 8–30 characters.</string>
<string name="textView_config_psd">The format of Admin password Error, please enter again.</string>
<string name="textView_config_psd8">Please enter a password with length between 8–32 characters.</string>
<string name="textView_tip_psd_error">The re-entered password doesn\'t match the password you just created. Please enter again.</string>
<string name="tip_invalid_phone_number">Please enter the correct mobile phone number or email address.</string>
<string name="str_resend">Resend</string>
<string name="toast_press_again_quit">Press once again to quit</string>
<string name="str_invalid_phone">Please enter the correct mobile phone number.</string>
<string name="yanzheng_error">Authentication failure</string>
<string name="register_success">Register Successfully</string>
<string name="register_error">Registration Failure</string>
<string name="login_error">Log in Failed</string>
<string name="sms_invalid">Verification code invalid</string>
<string name="sms_error">Incorrect verification code</string>
<string name="sms_send">Verification code sent as a text message</string>
<string name="sms_send_have_mobile">Registered user, please log in directly.</string>
<string name="tip_empty">Please enter%s</string>
<string name="textView_reset_password_success">Reset password OK</string>
<string name="textView_reset_password_error">Reset password failed</string>
<string name="textView_user_password_error">User name or password Error</string>
<string name="textView_router_title">Router Settings</string>
<string name="textView_router_title_lan">LAN settings</string>
<string name="textView_router_update">Update Assistant</string>
<string name="textView_merchant_title">Setup the Wi-Fi for business</string>
<string name="textView_customer_title">Setup the Wi-Fi for guest</string>
<string name="server_no_response">No response from Server</string>
<string name="str_about">About Sunmi Assistant</string>
<string name="str_logout">Log out</string>
<string name="str_store_info">Store Information</string>
<string name="str_help_feedback">Help and feedback</string>
<string name="tip_no_router_found">No Sunmi router was found</string>
<string name="tip_connect_router_insure">Please make sure that your mobile phone has been connected with the Wi-Fi of Sunmi outer.</string>
<string name="tip_wifi_is_matched">Please confirm whether the Wi-Fi has been connected with current router.</string>
<string name="str_setting">Settings</string>
<string name="tip_unregister">Unregistered user, please register first.</string>
<string name="str_register_now">Register now</string>
<string name="tip_input_phone_number">Enter the mobile number</string>
<string name="str_get_captcha">Get code</string>
<string name="tip_input_captcha">Enter the code</string>
<string name="str_store">Store</string>
<string name="str_tab_device">Device</string>
<string name="str_support">Service</string>
<string name="str_mine">Me</string>
<string name="tip_common_network_err">Network error…</string>
<string name="str_retrieve_password">Retrieve password</string>
<string name="str_captcha_sent">Verification code has been sent to：%s</string>
<string name="str_count_down_second">Resend(%d second)</string>
<string name="tip_kick_off">Your account has been logged into another device, if it\'s not your operation, please change your login password as soon as possible.</string>
<string name="tip_password_changed_login">Password changed, please login again</string>
<string name="tip_restart_success">Restart Successfully</string>
<string name="tip_restart_fail">Restart Failed</string>
<string name="tip_recovery_success">Restore factory settings successfully</string>
<string name="tip_recovery_fail">Restore factory settings failed</string>
<string name="str_recovery">Reset</string>
<string name="str_restart_router">Restart router</string>
<string name="str_restart_router_onekey">One key restart router</string>
<string name="str_unbind_router">Unbind</string>
<string name="str_change_manager_password">Admin password</string>
<string name="tip_unbind_success">Unbind successfully</string>
<string name="tip_unbind_fail">Unbind failed</string>
<string name="tip_password_change_success">Password change successfully</string>
<string name="tip_password_ori_success">Origin password Error</string>
<string name="tip_password_change_fail">Password change failed</string>
<string name="tip_password_is_null">Password cannot be null or all blank</string>
<string name="tip_password_inconformity">The new password don\'t match the confirmed password</string>
<string name="str_system_info">System information</string>
<string name="tip_not_support_remote">This operation only can be done under Wi-Fi through router, unable to proceed the remote operation.</string>
<string name="str_manual_input_ip">Static IP</string>
<string name="str_set_password">Set password</string>
<string name="str_input_captcha">Enter the verification code</string>
<string name="str_goto_register">Login</string>
<string name="tip_register_already">This mobile phone number has been registered as Sunmi account, you may log in directly.</string>
<string name="str_network_setting">Internet settings</string>
<string name="str_switch_network_way">Switch</string>
<string name="tip_set_success">Setup successfully</string>
<string name="tip_setting_fail">Save failed</string>
<string name="tip_setting_success">Save successfully</string>
<string name="str_auth_page">Authentication page</string>
<string name="tip_add_to_blacklist">Are you sure to add to blacklist? You may cancel this operation in block Wi-Fi freeloader & blacklist when needed.</string>
<string name="str_wechat_auth_setting">WeChat Authentication settings</string>
<string name="str_help">Help</string>
<string name="go_upgrade">Go upgrade</string>
<string name="tip_title_upgrade">New version found</string>
<string name="tip_message_upgrade">The current version is too old to carry out some functions, please upgrade to the latest version.</string>
<string name="tip_message_upgrade_set">The current version is too old, please upgrade to the latest one.</string>
<string name="str_add_sunmi_router">Add Sunmi router</string>
<string name="tip_input_router_password">For the safety of router, please enter the router admin password.</string>
<string name="tip_password_length_error">Please input a password with a length between 6–32 characters.</string>
<string name="str_online_device">Online devices</string>
<string name="toast_get_exception">Failed to get the information, please check your network, and try again.</string>
<string name="str_a_key_to_test_speed">Speed Test</string>
<string name="curr_router_manager_password">Any operation on LAN need to verify the Admin password.</string>
<string name="curr_router_error_password">The admin password has been invalid, please re-verify</string>
<string name="hint_input_password">Please enter the password</string>
<string name="hint_input_manger_password">Enter the password</string>
<string name="str_change_password">Change password</string>
<string name="str_bind_success">Bind successfully</string>
<string name="str_bind_fail">Bind failed</string>
<string name="tip_password_fail_too_often">You\'ve entered wrong password too many times, please retry in 5 minutes</string>
<string name="str_auth_manage">Authentication management</string>
<string name="str_mac_address">MAC Address</string>
<string name="str_save">Save</string>
<string name="str_business_category">Business category</string>
<string name="str_detail_addr">Detailed Address</string>
<string name="tip_addr_empty">Please enter the detailed address</string>
<string name="tip_over_limit_words">Exceed the length limit on characters</string>
<string name="tip_save_fail">Save failed</string>
<string name="str_edit_store_name">Edit store name</string>
<string name="tip_input_name">Please enter the name</string>
<string name="str_select_area">Select area</string>
<string name="tip_input_area">Please enter the address</string>
<string name="str_choose_please">Please choose</string>
<string name="tip_get_list_fail">Obtain list failed</string>
<string name="tip_now_new_version">The current version is the latest one</string>
<string name="tip_select_area">Please select the area</string>
<string name="tip_set_bandwidth">Are you sure to unable the function of intelligent bandwidth allocation？</string>
<string name="tip_set_more_bandwidth">Please enter the bandwidth parameter with a range of 1–1000.</string>
<string name="tip_inout_bandwidth">Bandwidth settings can not be null.</string>
<string name="title_quick_config_router">Please configure the connected Sunmi router</string>
<string name="str_add_device">Add device</string>
<string name="str_mine_device">My device</string>
<string name="str_more_settings">More settings</string>
<string name="str_encrypt_type">Encryption mode</string>
<string name="str_static_password">Static password</string>
<string name="str_dynamic_password">Dynamic password</string>
<string name="hint_dynamic_password">The generative rule of dynamic password: unpredictable eight digits, including numbers and letters.</string>
<string name="str_change_period">Change period</string>
<string name="str_hour">hour</string>
<string name="str_current_password">Current password</string>
<string name="str_name_space_right">Name</string>
<string name="str_password">Password</string>
<string name="textview_check_connecting">Now checking the type of internet connection, please wait…</string>
<string name="textview_config_connecting">Connecting to network now…</string>
<string name="tip_password_error">Incorrect password</string>
<string name="str_set_lead">Setup wizard</string>
<string name="str_return_set">Back to settings</string>
<string name="str_return_check">Detect again</string>
<string name="str_handle_set">Manual setup</string>
<string name="str_again_set">Setup again</string>
<string name="str_continue_set">Continue setup</string>
<string name="dia_title_disconnected">Unable to connect to the internet</string>
<string name="dia_msg_checknet">Please check the type of your internet connection is correct or not?</string>
<string name="str_86">+86</string>
<string name="tip_logout_success">Logout successfully</string>
<string name="tip_logout_fail">Logout exception</string>
<string name="msg_quit_confirm">Are you sure to quit the login?</string>
<string name="msg_clear_cache_confirm">Are you sure to clear the local cache?</string>
<string name="str_my_store">My store</string>
<string name="str_welcome_back">Welcome back</string>
<string name="tip_old_password_error">The origin password is wrong, please try again.</string>
<string name="tip_two_password_not_same">The re-entered password doesn\'t match the password you just created.</string>
<string name="tip_password_non_standard">The minimum length of password is 8 characters, must contain the numbers and letters, letters are case sensitive.</string>
<string name="test_speed">Speed test</string>
<string name="tip_test_speed_finish">Speed test finished</string>
<string name="tip_speed_testing">Speed testing…</string>
<string name="str_up_bandwidth">Upstream bandwidth</string>
<string name="str_down_bandwidth">Downstream bandwidth</string>
<string name="str_start_test">Start speed test</string>
<string name="str_tip_merge_exception">Account exception</string>
<string name="dialog_msg_merge">You have registered multiple accounts in different Sunmi platforms, for the safety of your accounts, need to merge your accounts. Click OK to merge.</string>
<string name="dialog_title_warm_tip">Warm tips</string>
<string name="str_now_connecting">Now connecting to the internet…</string>
<string name="str_tip_now_updating">Updating now, stop this process will affect using function，are you sure to quit?</string>
<string name="str_tip_backup_now">Backing up now, are you sure to quit?</string>
<string name="str_tip_recover_now">Recovering now, are you sure to quit？</string>
<string name="str_title_backup">Backup</string>
<string name="str_title_recover">Recover</string>
<string name="str_title_wx_set">Setup Wi-Fi connection to WeChat</string>
<string name="str_title_right_help">Help</string>
<string name="str_title_right_edit">Edit</string>
<string name="str_switch_success">Switch successfully</string>
<string name="str_switch_fail">Switch failed</string>
<string name="sunmi_register_agree">Create an account means you\'ve agree to the terms.</string>
<string name="str_psw_again">Re-enter password</string>
<string name="tip_input_psw_again"></string>
<string name="str_new_psw">New password</string>
<string name="tip_input_new_psw"></string>
<string name="tip_input_original_psw"></string>
<string name="str_original_psw">Original password</string>
<string name="str_modify">Modify</string>
<string name="str_phone">Mobile phone number</string>
<string name="str_unbind">Unbound</string>
<string name="str_email_address">Email address</string>
<string name="str_bound">Bound</string>
<string name="str_account_safety">Account safety</string>
<string name="str_clear_cache">Clear local cache</string>
<string name="tip_custom_psw_min_8">Please enter the business Wi–Fi password, the password length should be between 8–32 characters.</string>
<string name="tip_guest_psw_min_8">Please enter the guest Wi–Fi password, the password length should be between 8–32 characters.</string>
<string name="tip_psw_min_8">The minimum length of password should be at least 8 characters</string>
<string name="tip_input_wifi_name">Please enter the Wi-Fi name</string>
<string name="str_auto_obtain_ip">DHCP</string>
<string name="tip_please_input_dns">Please input the DNS</string>
<string name="str_first_dns">Primary DNS</string>
<string name="str_alternative_dns">Secondary DNS</string>
<string name="tip_input_alternative_dns">Please input the secondary DNS (optional)</string>
<string name="str_set_dns">Setup DNS</string>
<string name="str_auto">Automatic</string>
<string name="str_manual">Manual</string>
<string name="str_no_password">No password</string>
<string name="tip_wifi_setting_update">Settings on Wi-Fi changed, please re-connect when needed</string>
<string name="str_account">Account</string>
<string name="str_tip_input_name">Please enter the name</string>
<string name="str_tip_input32">Please enter 1–32 characters</string>
<string name="str_tip_input64">Please enter 1–64 characters</string>
<string name="str_dialog_cancel_edit">Are you sure to quit the edit?</string>
<string name="tip_input_correct_ip">Please input the correct IP address</string>
<string name="tip_input_correct_dns">Please input the correct DNS</string>
<string name="tip_input_correct_alternative_dns">Please input the correct secondary DNS</string>
<string name="tip_input_account">Please enter the account</string>
<string name="str_server_name">Server name</string>
<string name="hint_input_server_name">Please enter the server name(optional)</string>
<string name="str_broadband_dialup">PPPoE</string>
<string name="tip_input_subnet_mask">Please input the subnet mask</string>
<string name="tip_input_subnet_correct_mask">Please input the correct subnet mask</string>
<string name="tip_input_ip">Please input IP address</string>
<string name="tip_input_gateway">Please input the gateway</string>
<string name="tip_save_success">Saved successfully</string>
<string name="str_band_setting">Bandwidth Setting</string>
<string name="str_change_device_name">Change the device name</string>
<string name="tip_input_invalid_mac">Please input the valid MAC address</string>
<string name="str_backup_name">Backup name</string>
<string name="str_manual_add">Add manually</string>
<string name="str_wx_msg_logo">Please enter the Logo information</string>
<string name="str_wx_msg_welcome">Please enter the welcome message</string>
<string name="str_wx_msg_btn">Please enter the text for button</string>
<string name="str_wx_msg_copyright">Please enter the information for copyright</string>
<string name="str_title_user_list">User list</string>
<string name="str_connected_time">Connected time：</string>
<string name="str_offline_success">Offline successfully</string>
<string name="str_offline_fail">Offline failed</string>
<string name="str_offline">Offline</string>
<string name="str_wx_online">Please input the online time within 1~1440</string>
<string name="str_wx_idle">please input the idle and disconnect time within 1~1440</string>
<string name="str_wx_ssid">Please input SSID</string>
<string name="str_wx_shopId">Please enter the shop ID</string>
<string name="str_wx_appid">Please enter the APP ID</string>
<string name="str_wx_secretKey">Please enter the secretKey</string>
<string name="str_switch_open">ON</string>
<string name="str_switch_close">OFF</string>
<string name="str_find_new_version">Find new version</string>
<string name="str_text_normal">Normal</string>
<string name="str_text_exception">Exception</string>
<string name="str_text_pppoe">PPPoE</string>
<string name="str_text_input_ip">Static IP</string>
<string name="str_text_dhcp">Go online via DHCP</string>
<string name="str_auto_get_ip">(%s)</string>
<string name="str_manual_get_ip">(%s)</string>
<string name="str_manual_input_ip_bracket">(%s)</string>
<string name="str_auto_get_pppoe">(%s)</string>
<string name="str_manual_get_pppoe">(%s)</string>
<string name="str_tip_period">Please enter the period</string>
<string name="str_tip_wifi_not_be_same">The Wi-Fi name for business and guest can not be the same</string>
<string name="str_tip_mer_wifi_not_be_same">The Wi-Fi name for 2.4G and 5G can not be the same</string>
<string name="str_tip_setwifi_success">Settings on Wi-Fi successful, please re-confirm the Wi-Fi for network</string>
<string name="hint_input_first_dns">Please input the primary DNS</string>
<string name="str_ip_address">IP address</string>
<string name="tip_input_ip_address">Please input the IP address</string>
<string name="str_subnet_mask">Subnet mask</string>
<string name="str_default_gateway">Default gateway</string>
<string name="tip_input_default_gateway">Please input the default gateway</string>
<string name="tip_invalid_psw_change_period">Please enter the password change period（1～72）</string>
<string name="tip_input_valid_gateway">The default gateway and the IP address must be in the same network segment, the parameter of the default gateway and IP address can not be the same.</string>
<string name="str_ap_online">Online</string>
<string name="str_ap_offline">Offline</string>
<string name="str_ap_exception">Exception</string>
<string name="str_ap_unknown">——</string>
<string name="str_ap_bind_done">You have bound the current router</string>
<string name="str_ap_bind_no_again">You have bound the current router, please do not duplicate</string>
<string name="str_ap_bind_now">Bind now</string>
<string name="str_ap_bind_done1">The router you connected had been bound</string>
<string name="str_ap_bind">Bind router</string>
<string name="str_loading_store_message">Loading the store information…</string>
<string name="str_store_init_exception">Data initialization exception, please log in and load again</string>
<string name="str_call_unbind">If need bind, please contact %s for unbind first</string>
<string name="str_update_check_version">Checking new version for update…</string>
<string name="str_update_new_version">Already the latest version</string>
<string name="str_update_check_again">Check again</string>
<string name="str_update_now">Update now</string>
<string name="str_update_find_version">New version found</string>
<string name="str_updating">In the process of updating, do not switch off the router</string>
<string name="str_update_success">Congratulation! update successfully!</string>
<string name="str_update_knew">I knew</string>
<string name="str_update_fail">Sorry, update failed!</string>
<string name="str_update_fail_download">Download file failed, the reason is【%s】</string>
<string name="str_update_fail_check">File checksum error, the reason is【%s】</string>
<string name="str_update_again">Update again</string>
<string name="str_backup_now">Back up the settings now…</string>
<string name="str_backup_success">Backup successful</string>
<string name="str_backup_fail">Backup failure</string>
<string name="str_textview_sure">OK</string>
<string name="str_textview_again">Try again</string>
<string name="str_textview_set_file_name">Setup the file name</string>
<string name="str_backup_start">Start backup</string>
<string name="str_textview_input_file_name">Please enter the file name</string>
<string name="str_no_contain_emoji">Please use the English characters</string>
<string name="str_wifi_name">Please enter a Wi-Fi name with the length of 1~32 characters</string>
<string name="str_tip_wifi_set_success">Wi-Fi setup successfully</string>
<string name="str_tip_wifi_set_fail">Wi-Fi setup failed</string>
<string name="str_dialog_wifi_all_no_password">Potential security risk when having no password for business and guest Wi-Fi. Are you sure not to setup?</string>
<string name="str_dialog_wifi_mer_no_password">Potential security risk when having no password for main Wi-Fi. Are you sure not to setup?</string>
<string name="str_dialog_wifi_cus_no_password">Potential security risk when having no password for guest Wi-Fi. Are you sure not to setup?</string>
<string name="str_config_ap_ip">The format of IP address should be X.X.X.X., X is any whole number between 0 ~ 255. Please input again.</string>
<string name="str_config_ap_mask">The format of subnet mask should be X.X.X.X., X is any whole number between 0 ~ 255. Please input again.</string>
<string name="str_config_ap_gateway">The format of default gateway should be X.X.X.X., X is any whole number between 0 ~ 255. Please input again.</string>
<string name="str_config_ap_dns1">The format of primary DNS server should be X.X.X.X., X is any whole number between 0 ~ 255. Please input again.</string>
<string name="str_config_ap_dns2">The format of secondary DNS server should be X.X.X.X.,X is any whole number between 0 ~ 255. Please input again.</string>
<string name="str_config_ap_set_fail">The configuration on the types of internet connection is failure. Please confirm the input parameters.</string>
<string name="str_lan_set_ip">IP address for LAN</string>
<string name="str_lan_set_input_ip">Please input the IP address for LAN</string>
<string name="str_lan_set_mask">Subnet mask</string>
<string name="str_lan_set_input_mask">Please input the subnet mask</string>
<string name="str_lan_set_dhcp">DHCP server</string>
<string name="str_lan_set_tip">Address pool</string>
<string name="str_lan_set_ip_satrt">Start IP address</string>
<string name="str_lan_set_input_ip_start">Please input the start IP address</string>
<string name="str_lan_set_ip_end">End IP address</string>
<string name="str_lan_set_input_ip_end">Please input the end IP address</string>
<string name="str_ap_set_mer_wi_fi">Main Wi-Fi</string>
<string name="str_ap_set_cus_wi_fi">Guest Wi-Fi</string>
<string name="str_ap_set_lan">LAN settings</string>
<string name="str_ap_set_update">Update assistant</string>
<string name="str_ap_set_backup">Backup and restore</string>
<string name="str_wan_false">WAN port was not connected</string>
<string name="str_check_wan">Please check the network cable connection.</string>
<string name="str_select_dial">Please choose the type of internet connection</string>
<string name="str_checking_dial">Now checking the type of internet connection…</string>
<string name="tip_setting_open_success">Open successfully</string>
<string name="tip_setting_open_fail">Close successfully</string>
<string name="str_tip_input_ip">Please input the IP address</string>
<string name="str_tip_startip_no_same_enip">The start and end IP address can not be the same</string>
<string name="str_default_nickname">No nickname was set</string>
<string name="str_user_info">User information</string>
<string name="str_avatar">Avatar</string>
<string name="str_nickname">Nickname</string>
<string name="str_tip_set_relaucher">Reboot will stop all the current connections, around 1 minute to restart, later you might need to connect Wi-Fi manually.</string>
<string name="str_tip_set_unbind">Are you sure to unbind from Sunmi account?</string>
<string name="str_tip_set_factory_recover">After restore the factory settings, the router need to reconfigure the internet connection. Please pay attention to backup the configuration details.</string>
<string name="dialog_message_lan_save">After saving, if Wi-Fi is not connected or unable to access the internet, please try again to connect.</string>
<string name="str_set_username">Set a nickname</string>
<string name="tip_input_username">Please enter your nickname</string>
<string name="str_tip_lan_start_end_valid">The start and end IP address must be in the same network segment with LAN IP address</string>
<string name="str_startip_compare_endip">The parameter of start IP address must be less than the end IP address</string>
<string name="str_choose_from_album">Choose from album</string>
<string name="str_take_photo">Take photo</string>
<string name="str_version">v%s</string>
<string name="str_tip_img_upload_fail">Upload image failed</string>
<string name="str_tip_img_upload_success">Upload successfully</string>
<string name="str_tip_img_more_big">Upload image failed, please check the format and size of the image. Maximum size accepted for Logo is 128KB and background image is 512KB.</string>
<string name="str_status_open">ON</string>
<string name="str_status_close">OFF</string>
<string name="str_router_find">Find  </string>
<string name="str_router_find_dev">  devices connected in your network</string>
<string name="str_router_net_status">Network status：</string>
<string name="str_text_nornal">Normal</string>
<string name="str_router_offline">Router is offline, please take a look of the network</string>
<string name="str_router_connecting_exception">Router connection exception</string>
<string name="str_text_online">Online</string>
<string name="str_text_offline">Offline</string>
<string name="str_text_bandwith_tip">Allocation order on idle bandwidth: Sunmi devices>priority devices>less important devices</string>
<string name="str_bandwidth_up">Upstream bandwidth</string>
<string name="str_bandwidth_down">Downstream bandwidth</string>
<string name="str_bandwidth_set_tip">To avoid the excess or waste on up&downstream bandwidth, please set up the value of bandwidth based on the known real data.</string>
<string name="str_bandwidth_consult">If unclear, we suggest to return to auto detect, or ask your ISP.</string>
<string name="str_text_router_online">Online</string>
<string name="str_text_router_offline">Offline</string>
<string name="str_text_router_exception">Exception</string>
<string name="str_text_router_unknown">——</string>
<string name="str_add_store">Add store</string>
<string name="str_detail_addr_length">0/46</string>
<string name="str_test_speed_complete">Speed test finished</string>
<string name="str_net_disconnected">Network is disconnected, please check the network.</string>
<string name="str_fault_title">Fault diagnosis</string>
<string name="str_fault_checking">Diagnosis is in progress…</string>
<string name="str_fault_check_net_status">Check the connection status of network cable</string>
<string name="str_fault_is_get_ip">Check whether the external network has obtained the IP address.</string>
<string name="str_fault_wait_check">To to detected</string>
<string name="str_fault_check_internet">Check the Internet service</string>
<string name="str_fault_complete_diagnos">Diagnosis finished, problems found</string>
<string name="str_fault_diagnos_problems">Problems diagnosed：</string>
<string name="str_fault_no_internet">No internet service</string>
<string name="str_fault_reason">Possible reasons：</string>
<string name="str_fault_dial_erroe">The settings on the type of internet connection is wrong, or ISP exception.</string>
<string name="str_fault_resolve">Solutions:</string>
<string name="str_fault_set_dial">Please re-configure the type of internet connection, or contact with your ISP to handle.</string>
<string name="str_fault_diagnos_ok">Diagnosis finished, no problem found</string>
<string name="str_fault_net_cable_exception">Network cable exception</string>
<string name="str_fault_wan_exception">No network cable in WAN port</string>
<string name="str_fault_check_cat">Please check your network cable connection, or restart your modem and wait 2 minutes, then check again when modem is ready.</string>
<string name="str_wx_now_connecting">Current connection</string>
<string name="str_wx_user">user</string>
<string name="str_wx_cus_wifi_name">Current Wi-Fi name of guest：</string>
<string name="str_wx_help_goahead">Please go ahead</string>
<string name="str_wx_help_wechat">WeChat public platform</string>
<string name="str_wx_help_wechat_tip">Get the details of your WeChat public account, just one key may follow your WeChat public account when the customer log in the guest Wi-Fi. If you don\'t know how to have your WeChat public account, please click</string>
<string name="str_wx_help">\"help\"</string>
<string name="str_online_time">Online time：</string>
<string name="str_dev_signal">Signal Strength：</string>
<string name="str_dev_signal_good">Better</string>
<string name="str_dev_signal_nromal">Poor</string>
<string name="str_dev_flow">Consumption of network traffic:</string>
<string name="str_dev_black_add_success">Add to blacklist successfully</string>
<string name="str_dev_black_add_fail">Settings on blacklist exception</string>
<string name="str_open_success">Enable successfully</string>
<string name="str_cancel_success">Cancel successfully</string>
<string name="str_modify_success">Modify successfully</string>
<string name="str_modify_fail">Modify failed</string>
<string name="str_set_white_dev">Are you sure to setup the priority device?</string>
<string name="str_cancel_white_dev">Are you sure to cancel the priority device?</string>
<string name="str_text_allocation">SUNMI QoS</string>
<string name="tip_name_is_null">Name can not be null</string>
<string name="tip_store_create_success">Create store successfully</string>
<string name="tip_store_create_fail">Create store failed</string>
<string name="tip_location_success">Navigation success</string>
<string name="tip_location_fail">Current navigation failure</string>
<string name="str_button_open">Enable now</string>
<string name="str_dns_canot_same">The primary DNS can not be the same with secondary</string>
<string name="str_allocation_close_set">Disable the intelligent bandwidth allocation</string>
<string name="str_tip_open_success">Enable successfully</string>
<string name="str_tip_open_fail">Enable failed</string>
<string name="str_close_success">Close successfully</string>
<string name="str_close_fail">Close failed</string>
<string name="str_bandwidth_percent_set">Bandwidth Percent Setting</string>
<string name="str_dev_sunmi">Sunmi device</string>
<string name="str_dev_white">Priority device</string>
<string name="str_dev_normal">Normal device</string>
<string name="str_filename_length_less64">The length of file name should be less than 64 characters</string>
<string name="str_no_dev_list">No device list at this moment</string>
<string name="str_selected_dev">Please select the device to add into the blacklist</string>
<string name="str_recover_net">Restore the internet accessing</string>
<string name="str_antirubbing_net">Blacklist</string>
<string name="str_right_add_black">Add to blacklist</string>
<string name="str_dev_list_title">Device list</string>
<string name="str_online_dev_list">Online devices list</string>
<string name="str_left_cancel">Cancel</string>
<string name="str_text_no_dev_message">No device information at this moment</string>
<string name="str_add_white_dev">Add priority device</string>
<string name="str_add_no_auth_dev">Add the exemption certificate devices</string>
<string name="str_search_sunmi_dev">SUNMI Link</string>
<string name="str_text_priority_free_attest">Priority device with exemption certificate</string>
<string name="str_text_wired_free_attest">Wired port with exemption certificate</string>
<string name="str_text_add_free_attest">Add the devices with exemption certificate</string>
<string name="str_test_already_add">Added</string>
<string name="str_text_online_device_list">Online device list</string>
<string name="str_text_idle_disconnection">Idle disconnection</string>
<string name="str_text_minute">Minute</string>
<string name="str_text_three_vertical_point">. . .</string>
<string name="str_text_now_checking_network">Checking the status of internet connection…</string>
<string name="btn_udp_send">UDP sent</string>
<string name="btn_mqtt_get_user_msg">MQTT obtain user information</string>
<string name="btn_mqtt_connect">MQTT connect</string>
<string name="btn_untied">Unbind</string>
<string name="str_text_quick_configuration">Quick configuration</string>
<string name="btn_set_manager_pwd">Set the admin password</string>
<string name="btn_detection">Detection</string>
<string name="btn_jump_system_wifi">Jump to the Wi-Fi page of phone</string>
<string name="btn_wifi_setting">Wi-Fi setup</string>
<string name="btn_speed_detection">Speed test</string>
<string name="btn_bandwidth_qos">Bandwidth QoS</string>
<string name="btn_detect_network_connect_type">Detect the internet connection based on the connection type</string>
<string name="btn_get_linked_wan_msg">Obtain the WAN connection information</string>
<string name="str_text_dhcp_no_response">No response from DHCP server, please check whether need modify the internet connection</string>
<string name="str_still_continue_set">Continue setup?</string>
<string name="str_already_online">You may access to the internet now</string>
<string name="str_next_set_network_et">Next to setup the network bandwidth to unlock the function of intelligent bandwidth allocation</string>
<string name="str_enter_pwd">Please enter the broadband account name and password</string>
<string name="str_please_enter_account_pwd">Please enter the broadband account name and password provided by your Internet Service Provider</string>
<string name="str_set_network">Set the network bandwidth</string>
<string name="str_tip_operator">For an accurate distribution of network speed, please enter the correct up&downstream bandwidth. You may consult your ISP if anything unclear</string>
<string name="str_input_uplink">Please input the upstream bandwidth</string>
<string name="str_mbps">Mbps</string>
<string name="str_input_downlink">Please input the downstream bandwidth</string>
<string name="str_set_later">Setup later</string>
<string name="str_input_static_ip_msg">Please input the static IP address</string>
<string name="str_tip_ip_dns">Please enter the IP address, subnet mask, default gateway, DNS server which provide by your ISP.</string>
<string name="str_prefered_dns">Primary DNS server</string>
<string name="str_alternative_dns_optional">Secondary DNS server (Optional)</string>
<string name="str_auto_get_ip_dhcp">DHCP</string>
<string name="str_confirm_online_mode">Confirm the type of network connection</string>
<string name="str_tip_confirm_correct_online_mode">Please select the correct way of network connection. Consult your ISP if anything unclear</string>
<string name="str_pppoe">PPPoE</string>
<string name="str_manually_enter_ip">Input IP address (static IP)manually</string>
<string name="str_experience_more_featuures">Experience more functions</string>
<string name="str_text_lead_remote">Remote management</string>
<string name="str_network_device_management">Network devices management</string>
<string name="str_text_lead_allo">SUNMI QoS</string>
<string name="str_text_wx_link_wi_fi">Connect the WeChat to Wi-Fi</string>
<string name="btn_goto_register">Go to register</string>
<string name="btn_have_account_login">Existing account, please login directly</string>
<string name="str_WAN_port_not_connected">Detected that no connection cable on WAN port</string>
<string name="str_tip_check_cable">Please check the network cable connection, or restart the modem and wait 2 minutes, then check again when modem is ready.</string>
<string name="str_manually_set_online">Select the type of network connection manually</string>
<string name="str_set_manager_pwd">Set up the admin password</string>
<string name="str_tip_management_pwd_router">The Admin password is credential to log in and bind to the router</string>
<string name="str_hint_input_pwd_again">Please input the password again</string>
<string name="str_pwd_length">The length of password is 6~32 characters</string>
<string name="str_welocom_use_sunmi_router">Welcome for choosing Sunmi router</string>
<string name="str_tip_router_online">Few simple steps to setup your router to connect to the internet</string>
<string name="str_set_wifi">Set up the wireless network</string>
<string name="str_tip_set_wifi">Set the Wi-Fi name and password for business and guest</string>
<string name="str_merchant_wifi">Main Wi-Fi</string>
<string name="str_tip_suggestion_merchant">Main Wi-Fi (For devices and staff of store)</string>
<string name="hint_wifi_name">Enter Wi-Fi name</string>
<string name="hint_wifi_pwd">Wi-Fi password</string>
<string name="hint_wifi_mer_pwd">Enter Wi-Fi password</string>
<string name="hint_wifi_cus_pwd">Enter Wi-Fi password</string>
<string name="str_guest_wifi">Guest Wi-Fi</string>
<string name="str_tip_suggestion_guest">Guest Wi-Fi (For guests)</string>
<string name="str_text_priority_device">Priority devices can work with more fast and stable network speed</string>
<string name="str_add_priority_device">Add priority device</string>
<string name="str_no_priority_device">No priority devices at the moment</string>
<string name="str_text_device_list">Device list</string>
<string name="btn_login">Login</string>
<string name="hint_please_input_store_name">Please enter the store name</string>
<string name="str_similar_store">Similar store</string>
<string name="str_choose_from_phone_album">Album</string>
<string name="btn_add_store"> Add store</string>
<string name="str_store_name">Store name</string>
<string name="str_text_store_namee">Starbucks</string>
<string name="str_area">Area</string>
<string name="str_wallpaper">Wallpaper</string>
<string name="str_no_data">No data temporary</string>
<string name="str_signal_strength">Signal Strength: Normal</string>
<string name="str_traffic_consumption">Traffic consumption：0.00KB</string>
<string name="str_download_speed">Download speed </string>
<string name="str_upload_speed">Upload speed </string>
<string name="str_priority_online">Priority access to internet</string>
<string name="str_add_blacklist">Add to blacklist</string>
<string name="str_link_type">Connection type</string>
<string name="str_real_time_broadband_usage">Real time broadband usage</string>
<string name="str_sunmi_device">   Sunmi device</string>
<string name="str_bandwidth_usage">Bandwidth utilization0%</string>
<string name="str_priority_device">   priority device</string>
<string name="str_ordinary_device">   less important device</string>
<string name="str_tip_network_speed_allocation">The function of Intelligent Bandwidth Allocation is not enabled yet.</string>
<string name="str_tip_lead_allo">After the function of "Intelligent Bandwidth Allocation" enabled, router can allocate the bandwidth based on the configured priority levels and percentage for devices.</string>
<string name="str_total_bandwidth_setting">Set the total bandwidth</string>
<string name="str_set_extranet_bandwidth">Set the upstream and downstream bandwidth</string>
<string name="str_bandwidth_allocation_ratio_setting">Bandwidth allocation strategies</string>
<string name="set_minimum_bandwidth">Set the minimum bandwidth guarantee ratio</string>
<string name="str_tip_devices_using_most_traffic">View the devices who consume most traffic</string>
<string name="str_tip_block_devices">One-key to add the abnormal devices into blacklist</string>
<string name="str_blaklist_device">Devices in blacklist</string>
<string name="str_no_blacklist">No device in blacklist at the moment</string>
<string name="str_tip_no_restore">You shall have the backup files for restoring, please backup first.</string>
<string name="str_unclear_bandwidth">Have no idea on the volume of bandwidth?</string>
<string name="btn_immediate_speed_measurement">Test speed now</string>
<string name="str_blacklist_devices_no_internet">The devices in blacklist will be forbidden to access to the internet</string>
<string name="str_text_now_check_malfunction">Troubleshooting…</string>
<string name="str_text_diagnostic_problem">Problem diagnosis:</string>
<string name="str_diagnostic_problem">Problem diagnosing</string>
<string name="str_text_pending_detection">To be detected</string>
<string name="str_text_possion_reason">Possible reason：</string>
<string name="str_text_internet_connection_setting_error">Internet connection settings error</string>
<string name="str_text_solution">Solution:</string>
<string name="str_text_check_your_cable">Please check your network cable</string>
<string name="str_text_set_internet_access">Configure the type of internet connection</string>
<string name="str_no_backup_files_manage">No backup files were found for management</string>
<string name="str_network_status">Network status:——</string>
<string name="str_router_already_offline">Router is offline</string>
<string name="str_flood_ctrl_net">Blacklist</string>
<string name="str_discover_devices_connect_your_net">Found 0 device which connected with your network</string>
<string name="str_watch_devices">View</string>
<string name="str_smart_shop">Smart Shop</string>
<string name="str_search_nearby_sunmi_devices">SUNMI Link</string>
<string name="str_tip_sunmi_one_link">One-key to connect Sunmi devices nearly</string>
<string name="str_tip_provision_speed">Ensure the network speed for business devices</string>
<string name="str_priority_device_2">Priority List</string>
<string name="str_tip_set_priority_online">Priority devices take priority network access</string>
<string name="str_tip_improve_net_fans">No password needed, safe, block Wi-Fi freeloader</string>
<string name="str_text_hold_sunmi_device">Please hold your Sunmi devices</string>
<string name="str_text_wifi_turn_on_not_online">status of Wi-Fi function enabled but disconnected</string>
<string name="str_text_search_now">Search now</string>
<string name="str_text_connected_device">Connected devices</string>
<string name="str_text_no_connected_device">No connected device at this moment</string>
<string name="str_backup_router_config">Backup the configuration of router</string>
<string name="str_restore_router_config">Restore router configuration</string>
<string name="str_manage_backup_files">Backup file management</string>
<string name="btn_backup_all_config">Backup</string>
<string name="btn_only_bakup_wx_wifi">Only backup the settings of WeChat connecting Wi-Fi</string>
<string name="str_network_way">Internet connection type</string>
<string name="str_network_msg_now">Current information of internet connection</string>
<string name="str_networking_status">Networking status</string>
<string name="str_dual_frequency">Band Steering</string>
<string name="srt_tip_dual_frequncy">After the function of merging 2.4G and 5G signals is enabled, the terminal will automatic adapt the better signals. Recommend to enable this function.</string>
<string name="str_not_encypted">No encryption</string>
<string name="str_wpa2">Strong encryption (WPA2)</string>
<string name="str_wpa_wpa2">Hybrid encryption (WPA/WPA2)</string>
<string name="str_channel_bandwidth">Channel bandwidth</string>
<string name="str_wireless_channel">Wireless channel</string>
<string name="str_hide_network">Hide your internet connection</string>
<string name="str_text_restoring_config">Restoring configuration now…</string>
<string name="btn_restore_config">Restore configuration</string>
<string name="str_model">Model</string>
<string name="str_text_version">Version</string>
<string name="str_sn">Serial Number</string>
<string name="str_the_version">V1.0.0 Stable Version</string>
<string name="str_router_to_internet">Connect router to the internet</string>
<string name="str_checking_external_network">Speed testing on external network…</string>
<string name="str_tip_checking">Note: the progress of speed test will effect the network speed shortly.Resume immediately when completion.</string>
<string name="str_tip_wx_fans">Your customer may enjoy a quick Wi-Fi connection, and attract huge fans for your WeChat public account.</string>
<string name="str_tip_finish_set">Few simple steps to finish the settings easily</string>
<string name="str_welcome_page">Welcome page</string>
<string name="str_wx_public_msg">WeChat public account detail</string>
<string name="str_guest_online_time">Customer online time limit</string>
<string name="str_open_wx_connect_wif">Enable the Wi-Fi connection to WeChat</string>
<string name="str_current_access_user">Access 0 user currently</string>
<string name="str_two_way_guest_online">The following two ways to guide the customer accessing to the internet</string>
<string name="str_scan_QR_network">Scan QR code to connect the internet</string>
<string name="str_tip_wx_QR_network">Guide the customer to connect the internet by scan QR code via WeChat</string>
<string name="str_how_get_QR">How to get a QR code?</string>
<string name="str_tip_get_wx_QR">1.Go to the platform of WeChat public account, find "The Wi-Fi connection to WeChat -> the types of connection -> scan QR code to connect the internet -> Detail on download QR code" 2. Print the QR code and post in the store</string>
<string name="str_frome_welcome_network">Access the internet by "welcome page"</string>
<string name="str_tip_guest_wifi">Guide the customer connecting guest Wi-Fi manually, till pop up the welcome page, click button OK to access the internet</string>
<string name="str_now_guest_wifi_name">The current guest Wi-Fi name：SUNMI_XX_Guest</string>
<string name="str_online_user_devices">Online user devices</string>
<string name="str_no_user_access">No user access at this moment</string>
<string name="str_set_user_online_time">Set customer online time limit</string>
<string name="str_tip_set_user_online">Set the maximum allowed online time for customer, and the idle time for auto disconnection on checking out customers.</string>
<string name="str_allow_online_time">Allow online time</string>
<string name="str_allow_network_idle_time">Allow network idle time</string>
<string name="str_input_wx_msg">Fill in your WeChat public Account detail</string>
<string name="str_tip_get_wx_msg">Please get your WeChat public account detail in the WeChat public platform. Customer could one key follow your public account while they connect the guest Wi-Fi. Please click \'help\' if you don\'t know how to get a WeChat public account.</string>
<string name="hint_copy_paste_ssid">Please copy and paste SSID</string>
<string name="hint_copy_paste_shopid">Please copy and paste the shop ID</string>
<string name="hint_copy_paste_appid">Please copy and paste the APP ID</string>
<string name="hint_copy_paste_secretkey">Please copy and paste the secretkey</string>
<string name="str_logo_msg">Logo information</string>
<string name="hint_input_store_name">Please enter your brand/shop name</string>
<string name="str_welcome_msg">Welcome message</string>
<string name="str_input_wifi_welcome_words">Please enter your Wi-Fi welcome message</string>
<string name="str_btn_text">Text on button</string>
<string name="str_copyright_sound">Copyright statement</string>
<string name="hint_service_provider">Sunmi provides this Wi-Fi service</string>
<string name="str_add_img">Add image</string>
<string name="str_upload_logo">Upload logo image</string>
<string name="str_upload_background_img">Upload background image</string>
<string name="str_welcome">Welcome</string>
<string name="str_welcom_free_wifi">Welcome to connect this free on trial Wi-Fi</string>
<string name="btn_wx_connnect_wifi">Connect WeChat to Wi-Fi</string>
<string name="str_tip_jump_wx">Please change browser to re-try if unable to jump to WeChat</string>
<string name="str_tip_copyright">Sunmi© provides this wi-Fi service</string>
<string name="str_set_welcome_page">Set your welcome page</string>
<string name="str_tip_welome_page">Customer will see this welcome page when connect to guest Wi-Fi, you may also display your own logo here.</string>
<string name="btn_use_default">Use the default settings</string>
<string name="str_list_addition">Add a list</string>
<string name="str_switch_internet_access">Please select the type of the internet connection for switching</string>
<string name="str_msg_title_prompt">Message of title prompt</string>
<string name="str_displayed_msg_content">Display prompt information</string>
<string name="str_external_network_bandwidth">External network Bandwidth  </string>
<string name="str_search_no_sunmi_device">Found no Sunmi new device</string>
<string name="btn_cancel_search">Cancel search</string>
<string name="str_sumi">Sunmi</string>
<string name="str_priority">level of Priority</string>
<string name="str_text_cls">Normal</string>
<string name="str_minimum_guranteed_radio">Minimum guaranteed ratio</string>
<string name="str_merchant_wifi_access">Main Wi-Fi access</string>
<string name="str_just">Just now</string>
<string name="btn_version_update">Version for update</string>
<string name="btn_experience_now">Experience</string>
<string name="str_choose_backup_file">Choose the files for backup</string>
<string name="str_net_block">Ensure the core business working normally even the network is overload.</string>
<string name="str_net_can_work">Also can ensure the core business working normally。</string>
<string name="str_set_minimum_bandwidth">Upstream and downstream bandwidth</string>
<string name="str_set_bandwidth">Set the up&downstream bandwidth</string>
<string name="str_allocated_bandwidth">Total ratio</string>
<string name="str_minimum_bandwidth">The minimum bandwidth guarantee ratio</string>
<string name="str_app_download_progress">Download progress</string>
<string name="str_time_day">Day</string>
<string name="str_no_sd">No SD card found！</string>
<string name="str_please_open_camera">Please allow to open the camera！！</string>
<string name="str_open_sd">Please allow the operation on SD card！！</string>
<string name="str_selected_file">Please select the file</string>
<string name="str_selected">Please select</string>
<string name="str_sms_code_error">Failed to refresh the graph validation code</string>
<string name="str_input_manger_password">Please input the Admin password</string>
<string name="str_me">me</string>
<string name="str_store_load_error">Load store failed</string>
<string name="str_zero_dev">0 device</string>
<string name="str_get_pic_error">Failed to get the images from album</string>
<string name="str_pic_format_error">Failed to upload image, the format is not supported</string>
<string name="str_btn_cancel_white">Disable priortization</string>
<string name="str_dev_cancel_white">Remove the device from the list of priority devices</string>
<string name="str_dev_rocover_connected">The devices can connect to internet again</string>
<string name="str_password_no">No encryption</string>
<string name="str_password_strong">Strong encryption (WPA2)</string>
<string name="str_password_more">Hybrid encryption (WPA/WPA2)</string>
<string name="str_dialog_tip_delected_file">Are you sure to delete this backup file？</string>
<string name="str_btn_delete">Delete</string>
<string name="str_add_black_success">Add to blacklist successfully</string>
<string name="str_add_black_fail">Add to blacklist failed</string>
<string name="str_wifi_name_text">Name:</string>
<string name="str_wifi_no_psd">No password</string>
<string name="str_text_psd">Password：</string>
<string name="str_complete_config">Configuration complete</string>
<string name="str_recovering_config">Recovering the configuration now…</string>
<string name="str_recover_success">Recover successfully</string>
<string name="str_recover_fail">Recover failed</string>
<string name="str_btn_again">Try again</string>
<string name="str_sava_success">Save successfully</string>
<string name="str_save_fail">Save failed</string>
<string name="str_search_dev_num">new Sunmi devices</string>
<string name="str_search_connected_sunmi_net">Connected to Sunmi network automatically</string>
<string name="str_btn_know">I know</string>
<string name="str_search_now">Now searching…</string>
<string name="str_search_how_much">Found</string>
<string name="str_search_auth_connected_dev">Connected to Sunmi network automatically</string>
<string name="str_cancel_search">Cancel</string>
<string name="str_search_over">The search is over</string>
<string name="str_search_no_dev">No Sunmi devices found</string>
<string name="str_search_right_now">Search right now</string>
<string name="str_wifi_open_disconnected">The Wi-Fi function is enabled in a disconnection status.</string>
<string name="str_please_state_sunmi_dev">Please hold your Sunmi devices</string>
<string name="str_dev_no_sn">Device serial number is not exist</string>
<string name="tip_upgrade">tips for upgrading</string>
<string name="dlg_msg_ap_upgrade">It\'ll take 3 minutes for upgrade, and network will be disconnected during this period. Are you sure to upgrade now?</string>
<string name="dlg_msg_app_upgrade">The current version of APP is too old, please upgrade.</string>
<string name="dlg_msg_ap_upgrade_tip">The version of this router is too old to use this function, suggest to upgrade the router now.</string>
<string name="str_text_white">wire</string>
<string name="str_tip_router_offline">The current router is offline, no way to operate the router now.</string>
<string name="str_text_disconnected">The network is not giving strength</string>
<string name="str_text_tip_net">The furthest distance in the world is so ungelivable of network</string>
<string name="str_cannot_manager_ap">Can not operate the router at this moment</string>
<string name="str_firmware_update">Firmware update</string>
<string name="str_button_sure_set">Confirm settings</string>
<string name="str_set_cus_wifi">Set up guest Wi-Fi</string>
<string name="tip_ap_set_complete">Configuration on router complete</string>
<string name="str_text_remark_location">The location of the backup folder</string>
<string name="str_add_more_router">Add more router</string>
<string name="str_merchant_wifi_name">Wi-Fi name</string>
<string name="str_merchant_wifi_psd">Wi-Fi password</string>
<string name="str_guest_wifi_name">Wi-Fi name</string>
<string name="str_guest_wifi_password">Wi-Fi password</string>
<string name="str_button_bind">Bind now</string>
<string name="str_button_sure">OK</string>
<string name="str_text_bind_router">Admin Password</string>
<string name="str_text_input_name">Please enter the name</string>
<string name="str_text_net_set">Setup the network</string>
<string name="str_title_right_add_ap">Add router</string>
<string name="str_ap_search_num">Sunmi device：</string>
<string name="str_text_net">Network</string>
<string name="str_text_router">Router</string>
<string name="str_text_connecting">Online devices</string>
<string name="str_primary_search_find">Found your router</string>
<string name="str_primary_search_bind">Please bind your router</string>
<string name="str_primary_search_bind_done">The current router has been bound</string>
<string name="str_primary_search_already_bind">The current router has been bound, no need the duplicate binding</string>
<string name="str_primary_search_other_bind">This router has been bound</string>
<string name="str_router">Router</string>
<string name="str_add_router">Add router</string>
<string name="str_signal_quality">Signal quality：</string>
<string name="str_signal_status">Better</string>
<string name="str_signal_status_normal">Normal</string>
<string name="str_ip_adress_1">IP address:</string>
<string name="str_mac_adress_1">MAC address:</string>
<string name="str_last_ap">Main router:</string>
<string name="str_remark_setting">The location of the backup folder</string>
<string name="str_last_ap_none">None</string>
<string name="str_dialog_backup_name">Backup name</string>
<string name="str_password_no_contains_blank">Not allow any blank in a password</string>
<string name="str_bind_net_exception">Network exception, please bind again when online.</string>
<string name="str_delete">Delete</string>
<string name="str_unbind_ap_dialog_tip">Are you sure to delete the router?</string>
<string name="tip_delete_printer">Are you sure to remove the printer?</string>
<string name="tip_delete_ipc">Are you sure to remove the ipc?</string>
<string name="str_dialog_net_disconnected">Network disconnected, unable to delete</string>
<string name="str_remove">Remove</string>
<string name="str_input_less_32">Please enter 1–32 characters</string>
<string name="str_dialog_remove_child_ap">Are you sure to remove this router from the network?</string>
<string name="str_bind_other_done">The router has bound with other Sunmi account, you need to unbind that account then add again.</string>
<string name="str_again_try">Try again</string>
<string name="str_wifi_name_canont_null">Wi-Fi name can not be null</string>
<string name="tip_remove_success">Remove successfully</string>
<string name="tip_remove_fail">Remove failed</string>
<string name="str_btn_ap_restart">One key to restart</string>
<string name="str_reatart">Restart</string>
<string name="str_dev_model">Device model No.:</string>
<string name="str_restart_this_router">Are your sure to restart this router?</string>
<string name="str_refactory_this_router">Are you sure to restore the factory settings on this router?</string>
<string name="str_update_router">Router update</string>
<string name="str_btn_ap_update">One key update</string>
<string name="str_now_version">Current Version：</string>
<string name="str_new_version">Latest version：</string>
<string name="str_onekey_recovery">One key to restore factory settings</string>
<string name="str_refresh_pull">Pull down to refresh</string>
<string name="str_refresh_release">Release refresh</string>
<string name="str_refresh_loading">Loading…</string>
<string name="str_refresh_loading1">Refreshing…</string>
<string name="str_upguade_ap_fail">Upgrade failed</string>
<string name="str_upguade_ap_complete">Upgrade completed</string>
<string name="str_upguade_ap_start_fail">Enable upgrading failed</string>
<string name="str_upgrade_ap_download">Downloading the firmware</string>
<string name="str_upgrade_ap_check">Checking the upgrade version</string>
<string name="str_upgrade_ap_urgrading">Please do not power off the router during the firmware upgrading.</string>
<string name="str_upgrade_ap_find_newvesion">New version found</string>
<string name="str_upgrade_ap_cannot_exit">Upgrading now! Forcing to quit will effect the functions in normal use, please wait 2~3 minutes patiently.</string>
<string name="str_primary_connected_battery">1. Connect the power supply and network cable to the router, then wait till the system indicator stop blinking.</string>
<string name="str_primary_white">「white」</string>
<string name="str_primary_connected_mobile">2. Please connect the mobile phone to</string>
<string name="str_primary_connected_sunmixx">「SUNMI_XX」</string>
<string name="str_primary_connected_wireless">Wirless network</string>
<string name="str_upgrade_ap_text_newvesion">Latest version</string>
<string name="pull_to_refresh_from_bottom_pull_label">@string/pull_to_refresh_pull_label</string>
<string name="pull_to_refresh_from_bottom_release_label">@string/pull_to_refresh_release_label</string>
<string name="pull_to_refresh_from_bottom_refreshing_label">@string/pull_to_refresh_refreshing_label</string>
<string name="tip_psw_already_set">The admin password of router configured</string>
<string name="str_my_order">我的订单</string>
<string name="str_receive_address">收货地址</string>
<string name="str_coupon">优惠券</string>
<string name="str_my_setting">Settings</string>
<string name="str_store_manage">Store management</string>
<string name="str_current_company">当前商户</string>
<string name="text_day">天</string>
<string name="text_hour">时</string>
<string name="text_minute">分</string>
<string name="text_second">秒</string>
<string name="tip_input_company_name">请输入商户名称</string>
<string name="str_change_company_name">更改商户名称</string>
<string name="str_flow_selling">Selling Wi-Fi</string>
<string name="str_flow_selling_hour">Sell your Wi-Fi to the customers</string>
<string name="str_4g_lte">4G LTE</string>
<string name="str_priority_4g">Priority</string>
<string name="str_wan_priority">Wired Network Preferred</string>
<string name="str_4g_priority">3G/4G Preferred</string>
<string name="str_connected">Connected</string>
<string name="str_disconnected">Disconnected</string>
<string name="str_mine_store">我的店铺</string>
<string name="tip_ap_login_expire">路由器登录已过期，请重新登录</string>
<string name="tip_ap_psw_exception">账户初始化密码异常</string>
</resources>